name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash << 'EOF'
          # Настраиваем git для использования SSH (если еще не настроено)
          cd ~/chat-gft-deploy/frontend-source/chat-gft-client
          git remote set-url origin git@github.com:morislaflame/chat-gft-client.git 2>/dev/null || true
          
          # Обновляем код
          git pull origin main || {
            echo "⚠️  Git pull failed, trying to update..."
            git fetch origin main
            git reset --hard origin/main
          }
          
          cd ~/chat-gft-deploy
          ./deploy-safe.sh frontend
          EOF
      
      - name: Health check
        run: |
          sleep 30
          curl -f https://chatGFT.pro/ || exit 1