name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/chat-gft-deploy
            cd frontend-source/chat-gft-client
            git pull origin main
            cd ~/chat-gft-deploy
            ./deploy-safe.sh frontend
          EOF
      
      - name: Health check
        run: |
          sleep 30
          curl -f https://chatGFT.pro/ || exit 1